---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
  namespace: sock-shop
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8079
    targetPort: 8079
  selector:
    app: front-end
